### ISSUE TITLE
Add link to GitHub for contributors

### ISSUE THREAD

**Issue by StevenClontz** [lurchmath/lurchmath#2]
It'd be great if there was a link from https://proveitmath.org/lurch/ or https://lurchmath.github.io/lurchmath/ to https://github.com/lurchmath/lurchmath/ for potential contributors to engage with maintainers.

**Comment by nathancarter** [comment]
Great idea!

The proveitmath.org site is a temporary place just for Ken's spring 2024 students; it's not public-facing.

I just added a Help > About link to the app at lurchmath.github.io/lurchmath, which goes to our (tiny but getting started) documentation site.  There's a bunch of info there, including a link to the repo.

**Comment by StevenClontz** [comment]
Perfect! Thanks.
